version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # 로컬에서 Redis에 접근할 수 있도록 포트를 매핑합니다.
    networks:
      - redis-network
    volumes:
      - redis-data:/data # Redis 데이터를 유지하기 위한 볼륨 설정

networks:
  redis-network:

volumes:
  redis-data:
