spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/enjoytrip
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
  # spring ai 설정
  ai:
    openai:
      api-key: sk-proj-qSWEo2OZjZ8l5Jja6vCNT3BlbkFJpDTLHvHATkC2s2d2kyZD
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
  profiles:
    include: oauth

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/v1/docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: 1209600

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: enjoytrip-for-ssafy
    region:
      static: ap-northeast-2
    stack:
      auto: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          socket: DEBUG
#        kafka: DEBUG

